// Code generated by protoc-gen-zig
///! package mmc
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;
/// import package mmc.core
const mmc_core = @import("mmc/core.pb.zig");
/// import package mmc.command
const mmc_command = @import("mmc/command.pb.zig");
/// import package mmc.info
const mmc_info = @import("mmc/info.pb.zig");

pub const Request = struct {
    body: ?body_union,

    pub const _body_case = enum {
        core,
        command,
        info,
    };
    pub const body_union = union(_body_case) {
        core: mmc_core.Request,
        command: mmc_command.Request,
        info: mmc_info.Request,
        pub const _union_desc = .{
            .core = fd(1, .{ .SubMessage = {} }),
            .command = fd(2, .{ .SubMessage = {} }),
            .info = fd(3, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Response = struct {
    body: ?body_union,

    pub const _body_case = enum {
        core,
        command,
        info,
        request_error,
    };
    pub const body_union = union(_body_case) {
        core: mmc_core.Response,
        command: mmc_command.Response,
        info: mmc_info.Response,
        request_error: Response.RequestError,
        pub const _union_desc = .{
            .core = fd(1, .{ .SubMessage = {} }),
            .command = fd(2, .{ .SubMessage = {} }),
            .info = fd(3, .{ .SubMessage = {} }),
            .request_error = fd(4, .{ .Varint = .Simple }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub const RequestError = enum(i32) {
        MMC_REQUEST_ERROR_UNSPECIFIED = 0,
        MMC_REQUEST_ERROR_INVALID_MESSAGE = 1,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
