// Code generated by protoc-gen-zig
///! package mmc.core
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const Request = struct {
    kind: Request.Kind = @enumFromInt(0),

    pub const _desc_table = .{
        .kind = fd(1, .{ .Varint = .Simple }),
    };

    pub const Kind = enum(i32) {
        CORE_REQUEST_KIND_UNSPECIFIED = 0,
        CORE_REQUEST_KIND_API_VERSION = 1,
        CORE_REQUEST_KIND_SERVER_INFO = 2,
        CORE_REQUEST_KIND_LINE_CONFIG = 3,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Response = struct {
    body: ?body_union,

    pub const _body_case = enum {
        server,
        api_version,
        line_config,
        request_error,
    };
    pub const body_union = union(_body_case) {
        server: Response.Server,
        api_version: Response.SemanticVersion,
        line_config: Response.LineConfig,
        request_error: Response.RequestErrorKind,
        pub const _union_desc = .{
            .server = fd(1, .{ .SubMessage = {} }),
            .api_version = fd(2, .{ .SubMessage = {} }),
            .line_config = fd(3, .{ .SubMessage = {} }),
            .request_error = fd(4, .{ .Varint = .Simple }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub const RequestErrorKind = enum(i32) {
        CORE_REQUEST_ERROR_UNSPECIFIED = 0,
        CORE_REQUEST_ERROR_UNKNOWN_REQUEST = 1,
        _,
    };

    pub const LineConfig = struct {
        lines: ArrayList(Response.LineConfig.Line),

        pub const _desc_table = .{
            .lines = fd(1, .{ .List = .{ .SubMessage = {} } }),
        };

        pub const Line = struct {
            axes: u32 = 0,
            name: ManagedString = .Empty,

            pub const _desc_table = .{
                .axes = fd(1, .{ .Varint = .Simple }),
                .name = fd(2, .String),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const SemanticVersion = struct {
        major: u32 = 0,
        minor: u32 = 0,
        patch: u32 = 0,

        pub const _desc_table = .{
            .major = fd(1, .{ .Varint = .Simple }),
            .minor = fd(2, .{ .Varint = .Simple }),
            .patch = fd(3, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Server = struct {
        version: ?Response.SemanticVersion = null,
        name: ManagedString = .Empty,

        pub const _desc_table = .{
            .version = fd(1, .{ .SubMessage = {} }),
            .name = fd(2, .String),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
