// Code generated by protoc-gen-zig
///! package mmc.core
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const RequestKind = enum(i32) {
    REQUEST_KIND_UNSPECIFIED = 0,
    REQUEST_KIND_API_VERSION = 1,
    REQUEST_KIND_SERVER_VERSION = 2,
    REQUEST_KIND_LINE_CONFIG = 3,
    _,
};

pub const Request = struct {
    kind: RequestKind = @enumFromInt(0),

    pub const _desc_table = .{
        .kind = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Response = struct {
    body: ?body_union,

    pub const _body_case = enum {
        server_version,
        api_version,
        line_config,
    };
    pub const body_union = union(_body_case) {
        server_version: SemanticVersion,
        api_version: SemanticVersion,
        line_config: LineConfig,
        pub const _union_desc = .{
            .server_version = fd(1, .{ .SubMessage = {} }),
            .api_version = fd(2, .{ .SubMessage = {} }),
            .line_config = fd(3, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub const LineConfig = struct {
        lines: ArrayList(Line),

        pub const _desc_table = .{
            .lines = fd(1, .{ .List = .{ .SubMessage = {} } }),
        };

        pub const Line = struct {
            axes: u32 = 0,
            name: ManagedString = .Empty,

            pub const _desc_table = .{
                .axes = fd(1, .{ .Varint = .Simple }),
                .name = fd(2, .String),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const SemanticVersion = struct {
        major: u32 = 0,
        minor: u32 = 0,
        patch: u32 = 0,

        pub const _desc_table = .{
            .major = fd(1, .{ .Varint = .Simple }),
            .minor = fd(2, .{ .Varint = .Simple }),
            .patch = fd(3, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
