// Code generated by protoc-gen-zig
///! package mmc.info
const std = @import("std");

const pb = @import("protobuf");
const fd = pb.fd;

pub const Range = struct {
    start_id: u32 = 0,
    end_id: u32 = 0,

    pub const _desc_table = .{
        .start_id = fd(1, .{ .scalar = .uint32 }),
        .end_id = fd(2, .{ .scalar = .uint32 }),
    };

    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return pb.encode(writer, allocator, self);
    }

    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return pb.decode(@This(), reader, allocator);
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return pb.deinit(allocator, self);
    }

    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return pb.dupe(@This(), self, allocator);
    }

    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return pb.json.decode(@This(), input, options, allocator);
    }

    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return pb.json.encode(self, options, allocator);
    }

    // This method is used by std.json
    // internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return pb.json.parse(@This(), allocator, source, options);
    }

    // This method is used by std.json
    // internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return pb.json.stringify(@This(), self, jws);
    }
};

pub const Ids = struct {
    ids: std.ArrayListUnmanaged(u32) = .empty,

    pub const _desc_table = .{
        .ids = fd(1, .{ .packed_repeated = .{ .scalar = .uint32 } }),
    };

    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return pb.encode(writer, allocator, self);
    }

    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return pb.decode(@This(), reader, allocator);
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return pb.deinit(allocator, self);
    }

    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return pb.dupe(@This(), self, allocator);
    }

    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return pb.json.decode(@This(), input, options, allocator);
    }

    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return pb.json.encode(self, options, allocator);
    }

    // This method is used by std.json
    // internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return pb.json.parse(@This(), allocator, source, options);
    }

    // This method is used by std.json
    // internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return pb.json.stringify(@This(), self, jws);
    }
};

pub const Request = struct {
    body: ?body_union = null,

    pub const _body_case = enum {
        command,
        system,
    };
    pub const body_union = union(_body_case) {
        command: Request.Command,
        system: Request.System,
        pub const _desc_table = .{
            .command = fd(1, .submessage),
            .system = fd(2, .submessage),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .oneof = body_union }),
    };

    pub const Command = struct {
        id: ?u32 = null,

        pub const _desc_table = .{
            .id = fd(1, .{ .scalar = .uint32 }),
        };

        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return pb.encode(writer, allocator, self);
        }

        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return pb.decode(@This(), reader, allocator);
        }

        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return pb.deinit(allocator, self);
        }

        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return pb.dupe(@This(), self, allocator);
        }

        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return pb.json.decode(@This(), input, options, allocator);
        }

        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return pb.json.encode(self, options, allocator);
        }

        // This method is used by std.json
        // internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return pb.json.parse(@This(), allocator, source, options);
        }

        // This method is used by std.json
        // internally for serialization. DO NOT RENAME!
        pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
            return pb.json.stringify(@This(), self, jws);
        }
    };

    pub const System = struct {
        line_id: u32 = 0,
        driver: bool = false,
        axis: bool = false,
        carrier: bool = false,
        source: ?source_union = null,

        pub const _source_case = enum {
            driver_range,
            axis_range,
            carriers,
        };
        pub const source_union = union(_source_case) {
            driver_range: Range,
            axis_range: Range,
            carriers: Ids,
            pub const _desc_table = .{
                .driver_range = fd(5, .submessage),
                .axis_range = fd(6, .submessage),
                .carriers = fd(7, .submessage),
            };
        };

        pub const _desc_table = .{
            .line_id = fd(1, .{ .scalar = .uint32 }),
            .driver = fd(2, .{ .scalar = .bool }),
            .axis = fd(3, .{ .scalar = .bool }),
            .carrier = fd(4, .{ .scalar = .bool }),
            .source = fd(null, .{ .oneof = source_union }),
        };

        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return pb.encode(writer, allocator, self);
        }

        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return pb.decode(@This(), reader, allocator);
        }

        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return pb.deinit(allocator, self);
        }

        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return pb.dupe(@This(), self, allocator);
        }

        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return pb.json.decode(@This(), input, options, allocator);
        }

        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return pb.json.encode(self, options, allocator);
        }

        // This method is used by std.json
        // internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return pb.json.parse(@This(), allocator, source, options);
        }

        // This method is used by std.json
        // internally for serialization. DO NOT RENAME!
        pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
            return pb.json.stringify(@This(), self, jws);
        }
    };

    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return pb.encode(writer, allocator, self);
    }

    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return pb.decode(@This(), reader, allocator);
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return pb.deinit(allocator, self);
    }

    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return pb.dupe(@This(), self, allocator);
    }

    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return pb.json.decode(@This(), input, options, allocator);
    }

    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return pb.json.encode(self, options, allocator);
    }

    // This method is used by std.json
    // internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return pb.json.parse(@This(), allocator, source, options);
    }

    // This method is used by std.json
    // internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return pb.json.stringify(@This(), self, jws);
    }
};

pub const Response = struct {
    body: ?body_union = null,

    pub const _body_case = enum {
        commands,
        system,
        request_error,
    };
    pub const body_union = union(_body_case) {
        commands: Response.Commands,
        system: Response.System,
        request_error: Response.RequestErrorKind,
        pub const _desc_table = .{
            .commands = fd(1, .submessage),
            .system = fd(2, .submessage),
            .request_error = fd(3, .@"enum"),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .oneof = body_union }),
    };

    pub const RequestErrorKind = enum(i32) {
        INFO_REQUEST_ERROR_UNSPECIFIED = 0,
        INFO_REQUEST_ERROR_INVALID_LINE = 1,
        INFO_REQUEST_ERROR_INVALID_AXIS = 2,
        INFO_REQUEST_ERROR_INVALID_DRIVER = 3,
        INFO_REQUEST_ERROR_CARRIER_NOT_FOUND = 4,
        INFO_REQUEST_ERROR_CC_LINK_DISCONNECTED = 5,
        INFO_REQUEST_ERROR_MISSING_PARAMETER = 6,
        INFO_REQUEST_ERROR_COMMAND_NOT_FOUND = 7,
        _,
    };

    pub const Commands = struct {
        commands: std.ArrayListUnmanaged(Response.Commands.Command) = .empty,

        pub const _desc_table = .{
            .commands = fd(1, .{ .repeated = .submessage }),
        };

        pub const Command = struct {
            id: u32 = 0,
            status: Response.Commands.Command.Status = @enumFromInt(0),
            error_response: ?Response.Commands.Command.ErrorKind = null,

            pub const _desc_table = .{
                .id = fd(1, .{ .scalar = .uint32 }),
                .status = fd(2, .@"enum"),
                .error_response = fd(3, .@"enum"),
            };

            pub const Status = enum(i32) {
                STATUS_UNSPECIFIED = 0,
                STATUS_PROGRESSING = 1,
                STATUS_COMPLETED = 2,
                STATUS_FAILED = 3,
                STATUS_QUEUED = 4,
                _,
            };

            pub const ErrorKind = enum(i32) {
                ERROR_KIND_UNSPECIFIED = 0,
                ERROR_KIND_INVALID_COMMAND = 1,
                ERROR_KIND_CARRIER_NOT_FOUND = 2,
                ERROR_KIND_HOMING_FAILED = 3,
                ERROR_KIND_INVALID_PARAMETER = 4,
                ERROR_KIND_INVALID_SYSTEM_STATE = 5,
                ERROR_KIND_CARRIER_ALREADY_EXISTS = 6,
                ERROR_KIND_INVALID_AXIS = 7,
                ERROR_KIND_CC_LINK_DISCONNECTED = 8,
                ERROR_KIND_OUT_OF_MEMORY = 9,
                _,
            };

            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return pb.encode(writer, allocator, self);
            }

            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return pb.decode(@This(), reader, allocator);
            }

            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return pb.deinit(allocator, self);
            }

            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return pb.dupe(@This(), self, allocator);
            }

            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return pb.json.decode(@This(), input, options, allocator);
            }

            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return pb.json.encode(self, options, allocator);
            }

            // This method is used by std.json
            // internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return pb.json.parse(@This(), allocator, source, options);
            }

            // This method is used by std.json
            // internally for serialization. DO NOT RENAME!
            pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                return pb.json.stringify(@This(), self, jws);
            }
        };

        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return pb.encode(writer, allocator, self);
        }

        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return pb.decode(@This(), reader, allocator);
        }

        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return pb.deinit(allocator, self);
        }

        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return pb.dupe(@This(), self, allocator);
        }

        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return pb.json.decode(@This(), input, options, allocator);
        }

        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return pb.json.encode(self, options, allocator);
        }

        // This method is used by std.json
        // internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return pb.json.parse(@This(), allocator, source, options);
        }

        // This method is used by std.json
        // internally for serialization. DO NOT RENAME!
        pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
            return pb.json.stringify(@This(), self, jws);
        }
    };

    pub const System = struct {
        line_id: u32 = 0,
        driver_infos: std.ArrayListUnmanaged(Response.System.Driver.Info) = .empty,
        driver_errors: std.ArrayListUnmanaged(Response.System.Driver.Error) = .empty,
        axis_infos: std.ArrayListUnmanaged(Response.System.Axis.Info) = .empty,
        axis_errors: std.ArrayListUnmanaged(Response.System.Axis.Error) = .empty,
        carrier_infos: std.ArrayListUnmanaged(Response.System.Carrier.Info) = .empty,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .scalar = .uint32 }),
            .driver_infos = fd(2, .{ .repeated = .submessage }),
            .driver_errors = fd(3, .{ .repeated = .submessage }),
            .axis_infos = fd(4, .{ .repeated = .submessage }),
            .axis_errors = fd(5, .{ .repeated = .submessage }),
            .carrier_infos = fd(6, .{ .repeated = .submessage }),
        };

        pub const Axis = struct {
            pub const _desc_table = .{};

            pub const Info = struct {
                id: u32 = 0,
                motor_enabled: bool = false,
                waiting_pull: bool = false,
                waiting_push: bool = false,
                carrier_id: u32 = 0,
                hall_alarm: ?Response.System.Axis.Info.HallAlarm = null,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .motor_enabled = fd(2, .{ .scalar = .bool }),
                    .waiting_pull = fd(3, .{ .scalar = .bool }),
                    .waiting_push = fd(4, .{ .scalar = .bool }),
                    .carrier_id = fd(5, .{ .scalar = .uint32 }),
                    .hall_alarm = fd(6, .submessage),
                };

                pub const HallAlarm = struct {
                    back: bool = false,
                    front: bool = false,

                    pub const _desc_table = .{
                        .back = fd(1, .{ .scalar = .bool }),
                        .front = fd(2, .{ .scalar = .bool }),
                    };

                    pub fn encode(
                        self: @This(),
                        writer: *std.Io.Writer,
                        allocator: std.mem.Allocator,
                    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                        return pb.encode(writer, allocator, self);
                    }

                    pub fn decode(
                        reader: *std.Io.Reader,
                        allocator: std.mem.Allocator,
                    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                        return pb.decode(@This(), reader, allocator);
                    }

                    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                        return pb.deinit(allocator, self);
                    }

                    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                        return pb.dupe(@This(), self, allocator);
                    }

                    pub fn jsonDecode(
                        input: []const u8,
                        options: std.json.ParseOptions,
                        allocator: std.mem.Allocator,
                    ) !std.json.Parsed(@This()) {
                        return pb.json.decode(@This(), input, options, allocator);
                    }

                    pub fn jsonEncode(
                        self: @This(),
                        options: std.json.Stringify.Options,
                        allocator: std.mem.Allocator,
                    ) ![]const u8 {
                        return pb.json.encode(self, options, allocator);
                    }

                    // This method is used by std.json
                    // internally for deserialization. DO NOT RENAME!
                    pub fn jsonParse(
                        allocator: std.mem.Allocator,
                        source: anytype,
                        options: std.json.ParseOptions,
                    ) !@This() {
                        return pb.json.parse(@This(), allocator, source, options);
                    }

                    // This method is used by std.json
                    // internally for serialization. DO NOT RENAME!
                    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                        return pb.json.stringify(@This(), self, jws);
                    }
                };

                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return pb.encode(writer, allocator, self);
                }

                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return pb.decode(@This(), reader, allocator);
                }

                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return pb.deinit(allocator, self);
                }

                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return pb.dupe(@This(), self, allocator);
                }

                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return pb.json.decode(@This(), input, options, allocator);
                }

                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return pb.json.encode(self, options, allocator);
                }

                // This method is used by std.json
                // internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return pb.json.parse(@This(), allocator, source, options);
                }

                // This method is used by std.json
                // internally for serialization. DO NOT RENAME!
                pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                    return pb.json.stringify(@This(), self, jws);
                }
            };

            pub const Error = struct {
                id: u32 = 0,
                overcurrent: bool = false,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .overcurrent = fd(2, .{ .scalar = .bool }),
                };

                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return pb.encode(writer, allocator, self);
                }

                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return pb.decode(@This(), reader, allocator);
                }

                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return pb.deinit(allocator, self);
                }

                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return pb.dupe(@This(), self, allocator);
                }

                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return pb.json.decode(@This(), input, options, allocator);
                }

                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return pb.json.encode(self, options, allocator);
                }

                // This method is used by std.json
                // internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return pb.json.parse(@This(), allocator, source, options);
                }

                // This method is used by std.json
                // internally for serialization. DO NOT RENAME!
                pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                    return pb.json.stringify(@This(), self, jws);
                }
            };

            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return pb.encode(writer, allocator, self);
            }

            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return pb.decode(@This(), reader, allocator);
            }

            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return pb.deinit(allocator, self);
            }

            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return pb.dupe(@This(), self, allocator);
            }

            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return pb.json.decode(@This(), input, options, allocator);
            }

            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return pb.json.encode(self, options, allocator);
            }

            // This method is used by std.json
            // internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return pb.json.parse(@This(), allocator, source, options);
            }

            // This method is used by std.json
            // internally for serialization. DO NOT RENAME!
            pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                return pb.json.stringify(@This(), self, jws);
            }
        };

        pub const Driver = struct {
            pub const _desc_table = .{};

            pub const Info = struct {
                id: u32 = 0,
                connected: bool = false,
                available: bool = false,
                servo_enabled: bool = false,
                stopped: bool = false,
                paused: bool = false,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .connected = fd(2, .{ .scalar = .bool }),
                    .available = fd(3, .{ .scalar = .bool }),
                    .servo_enabled = fd(4, .{ .scalar = .bool }),
                    .stopped = fd(5, .{ .scalar = .bool }),
                    .paused = fd(6, .{ .scalar = .bool }),
                };

                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return pb.encode(writer, allocator, self);
                }

                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return pb.decode(@This(), reader, allocator);
                }

                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return pb.deinit(allocator, self);
                }

                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return pb.dupe(@This(), self, allocator);
                }

                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return pb.json.decode(@This(), input, options, allocator);
                }

                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return pb.json.encode(self, options, allocator);
                }

                // This method is used by std.json
                // internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return pb.json.parse(@This(), allocator, source, options);
                }

                // This method is used by std.json
                // internally for serialization. DO NOT RENAME!
                pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                    return pb.json.stringify(@This(), self, jws);
                }
            };

            pub const Error = struct {
                id: u32 = 0,
                control_loop_time_exceeded: bool = false,
                inverter_overheat: bool = false,
                power_error: ?Response.System.Driver.Error.PowerError = null,
                communication_error: ?Response.System.Driver.Error.CommError = null,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .control_loop_time_exceeded = fd(2, .{ .scalar = .bool }),
                    .inverter_overheat = fd(3, .{ .scalar = .bool }),
                    .power_error = fd(4, .submessage),
                    .communication_error = fd(5, .submessage),
                };

                pub const CommError = struct {
                    from_prev: bool = false,
                    from_next: bool = false,

                    pub const _desc_table = .{
                        .from_prev = fd(1, .{ .scalar = .bool }),
                        .from_next = fd(2, .{ .scalar = .bool }),
                    };

                    pub fn encode(
                        self: @This(),
                        writer: *std.Io.Writer,
                        allocator: std.mem.Allocator,
                    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                        return pb.encode(writer, allocator, self);
                    }

                    pub fn decode(
                        reader: *std.Io.Reader,
                        allocator: std.mem.Allocator,
                    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                        return pb.decode(@This(), reader, allocator);
                    }

                    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                        return pb.deinit(allocator, self);
                    }

                    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                        return pb.dupe(@This(), self, allocator);
                    }

                    pub fn jsonDecode(
                        input: []const u8,
                        options: std.json.ParseOptions,
                        allocator: std.mem.Allocator,
                    ) !std.json.Parsed(@This()) {
                        return pb.json.decode(@This(), input, options, allocator);
                    }

                    pub fn jsonEncode(
                        self: @This(),
                        options: std.json.Stringify.Options,
                        allocator: std.mem.Allocator,
                    ) ![]const u8 {
                        return pb.json.encode(self, options, allocator);
                    }

                    // This method is used by std.json
                    // internally for deserialization. DO NOT RENAME!
                    pub fn jsonParse(
                        allocator: std.mem.Allocator,
                        source: anytype,
                        options: std.json.ParseOptions,
                    ) !@This() {
                        return pb.json.parse(@This(), allocator, source, options);
                    }

                    // This method is used by std.json
                    // internally for serialization. DO NOT RENAME!
                    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                        return pb.json.stringify(@This(), self, jws);
                    }
                };

                pub const PowerError = struct {
                    overvoltage: bool = false,
                    undervoltage: bool = false,

                    pub const _desc_table = .{
                        .overvoltage = fd(1, .{ .scalar = .bool }),
                        .undervoltage = fd(2, .{ .scalar = .bool }),
                    };

                    pub fn encode(
                        self: @This(),
                        writer: *std.Io.Writer,
                        allocator: std.mem.Allocator,
                    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                        return pb.encode(writer, allocator, self);
                    }

                    pub fn decode(
                        reader: *std.Io.Reader,
                        allocator: std.mem.Allocator,
                    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                        return pb.decode(@This(), reader, allocator);
                    }

                    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                        return pb.deinit(allocator, self);
                    }

                    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                        return pb.dupe(@This(), self, allocator);
                    }

                    pub fn jsonDecode(
                        input: []const u8,
                        options: std.json.ParseOptions,
                        allocator: std.mem.Allocator,
                    ) !std.json.Parsed(@This()) {
                        return pb.json.decode(@This(), input, options, allocator);
                    }

                    pub fn jsonEncode(
                        self: @This(),
                        options: std.json.Stringify.Options,
                        allocator: std.mem.Allocator,
                    ) ![]const u8 {
                        return pb.json.encode(self, options, allocator);
                    }

                    // This method is used by std.json
                    // internally for deserialization. DO NOT RENAME!
                    pub fn jsonParse(
                        allocator: std.mem.Allocator,
                        source: anytype,
                        options: std.json.ParseOptions,
                    ) !@This() {
                        return pb.json.parse(@This(), allocator, source, options);
                    }

                    // This method is used by std.json
                    // internally for serialization. DO NOT RENAME!
                    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                        return pb.json.stringify(@This(), self, jws);
                    }
                };

                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return pb.encode(writer, allocator, self);
                }

                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return pb.decode(@This(), reader, allocator);
                }

                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return pb.deinit(allocator, self);
                }

                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return pb.dupe(@This(), self, allocator);
                }

                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return pb.json.decode(@This(), input, options, allocator);
                }

                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return pb.json.encode(self, options, allocator);
                }

                // This method is used by std.json
                // internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return pb.json.parse(@This(), allocator, source, options);
                }

                // This method is used by std.json
                // internally for serialization. DO NOT RENAME!
                pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                    return pb.json.stringify(@This(), self, jws);
                }
            };

            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return pb.encode(writer, allocator, self);
            }

            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return pb.decode(@This(), reader, allocator);
            }

            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return pb.deinit(allocator, self);
            }

            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return pb.dupe(@This(), self, allocator);
            }

            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return pb.json.decode(@This(), input, options, allocator);
            }

            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return pb.json.encode(self, options, allocator);
            }

            // This method is used by std.json
            // internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return pb.json.parse(@This(), allocator, source, options);
            }

            // This method is used by std.json
            // internally for serialization. DO NOT RENAME!
            pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                return pb.json.stringify(@This(), self, jws);
            }
        };

        pub const Carrier = struct {
            pub const _desc_table = .{};

            pub const Info = struct {
                id: u32 = 0,
                position: f32 = 0,
                axis: ?Response.System.Carrier.Info.Axis = null,
                cas: ?Response.System.Carrier.Info.Cas = null,
                state: Response.System.Carrier.Info.State = @enumFromInt(0),

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .position = fd(2, .{ .scalar = .float }),
                    .axis = fd(3, .submessage),
                    .cas = fd(4, .submessage),
                    .state = fd(5, .@"enum"),
                };

                pub const State = enum(i32) {
                    CARRIER_STATE_NONE = 0,
                    CARRIER_STATE_CALIBRATING = 1,
                    CARRIER_STATE_CALIBRATE_COMPLETED = 2,
                    CARRIER_STATE_MOVING = 3,
                    CARRIER_STATE_MOVE_COMPLETED = 4,
                    CARRIER_STATE_ISOLATING = 5,
                    CARRIER_STATE_ISOLATE_COMPLETED = 6,
                    CARRIER_STATE_PUSHING = 7,
                    CARRIER_STATE_PUSH_COMPLETED = 8,
                    CARRIER_STATE_PULLING = 9,
                    CARRIER_STATE_PULL_COMPLETED = 10,
                    CARRIER_STATE_OVERCURRENT = 11,
                    _,
                };

                pub const Axis = struct {
                    main: u32 = 0,
                    auxiliary: ?u32 = null,

                    pub const _desc_table = .{
                        .main = fd(1, .{ .scalar = .uint32 }),
                        .auxiliary = fd(2, .{ .scalar = .uint32 }),
                    };

                    pub fn encode(
                        self: @This(),
                        writer: *std.Io.Writer,
                        allocator: std.mem.Allocator,
                    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                        return pb.encode(writer, allocator, self);
                    }

                    pub fn decode(
                        reader: *std.Io.Reader,
                        allocator: std.mem.Allocator,
                    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                        return pb.decode(@This(), reader, allocator);
                    }

                    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                        return pb.deinit(allocator, self);
                    }

                    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                        return pb.dupe(@This(), self, allocator);
                    }

                    pub fn jsonDecode(
                        input: []const u8,
                        options: std.json.ParseOptions,
                        allocator: std.mem.Allocator,
                    ) !std.json.Parsed(@This()) {
                        return pb.json.decode(@This(), input, options, allocator);
                    }

                    pub fn jsonEncode(
                        self: @This(),
                        options: std.json.Stringify.Options,
                        allocator: std.mem.Allocator,
                    ) ![]const u8 {
                        return pb.json.encode(self, options, allocator);
                    }

                    // This method is used by std.json
                    // internally for deserialization. DO NOT RENAME!
                    pub fn jsonParse(
                        allocator: std.mem.Allocator,
                        source: anytype,
                        options: std.json.ParseOptions,
                    ) !@This() {
                        return pb.json.parse(@This(), allocator, source, options);
                    }

                    // This method is used by std.json
                    // internally for serialization. DO NOT RENAME!
                    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                        return pb.json.stringify(@This(), self, jws);
                    }
                };

                pub const Cas = struct {
                    enabled: bool = false,
                    triggered: bool = false,

                    pub const _desc_table = .{
                        .enabled = fd(1, .{ .scalar = .bool }),
                        .triggered = fd(2, .{ .scalar = .bool }),
                    };

                    pub fn encode(
                        self: @This(),
                        writer: *std.Io.Writer,
                        allocator: std.mem.Allocator,
                    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                        return pb.encode(writer, allocator, self);
                    }

                    pub fn decode(
                        reader: *std.Io.Reader,
                        allocator: std.mem.Allocator,
                    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                        return pb.decode(@This(), reader, allocator);
                    }

                    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                        return pb.deinit(allocator, self);
                    }

                    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                        return pb.dupe(@This(), self, allocator);
                    }

                    pub fn jsonDecode(
                        input: []const u8,
                        options: std.json.ParseOptions,
                        allocator: std.mem.Allocator,
                    ) !std.json.Parsed(@This()) {
                        return pb.json.decode(@This(), input, options, allocator);
                    }

                    pub fn jsonEncode(
                        self: @This(),
                        options: std.json.Stringify.Options,
                        allocator: std.mem.Allocator,
                    ) ![]const u8 {
                        return pb.json.encode(self, options, allocator);
                    }

                    // This method is used by std.json
                    // internally for deserialization. DO NOT RENAME!
                    pub fn jsonParse(
                        allocator: std.mem.Allocator,
                        source: anytype,
                        options: std.json.ParseOptions,
                    ) !@This() {
                        return pb.json.parse(@This(), allocator, source, options);
                    }

                    // This method is used by std.json
                    // internally for serialization. DO NOT RENAME!
                    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                        return pb.json.stringify(@This(), self, jws);
                    }
                };

                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return pb.encode(writer, allocator, self);
                }

                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return pb.decode(@This(), reader, allocator);
                }

                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return pb.deinit(allocator, self);
                }

                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return pb.dupe(@This(), self, allocator);
                }

                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return pb.json.decode(@This(), input, options, allocator);
                }

                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return pb.json.encode(self, options, allocator);
                }

                // This method is used by std.json
                // internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return pb.json.parse(@This(), allocator, source, options);
                }

                // This method is used by std.json
                // internally for serialization. DO NOT RENAME!
                pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                    return pb.json.stringify(@This(), self, jws);
                }
            };

            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return pb.encode(writer, allocator, self);
            }

            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return pb.decode(@This(), reader, allocator);
            }

            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return pb.deinit(allocator, self);
            }

            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return pb.dupe(@This(), self, allocator);
            }

            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return pb.json.decode(@This(), input, options, allocator);
            }

            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return pb.json.encode(self, options, allocator);
            }

            // This method is used by std.json
            // internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return pb.json.parse(@This(), allocator, source, options);
            }

            // This method is used by std.json
            // internally for serialization. DO NOT RENAME!
            pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
                return pb.json.stringify(@This(), self, jws);
            }
        };

        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return pb.encode(writer, allocator, self);
        }

        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return pb.decode(@This(), reader, allocator);
        }

        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return pb.deinit(allocator, self);
        }

        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return pb.dupe(@This(), self, allocator);
        }

        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return pb.json.decode(@This(), input, options, allocator);
        }

        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return pb.json.encode(self, options, allocator);
        }

        // This method is used by std.json
        // internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return pb.json.parse(@This(), allocator, source, options);
        }

        // This method is used by std.json
        // internally for serialization. DO NOT RENAME!
        pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
            return pb.json.stringify(@This(), self, jws);
        }
    };

    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return pb.encode(writer, allocator, self);
    }

    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (pb.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return pb.decode(@This(), reader, allocator);
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return pb.deinit(allocator, self);
    }

    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return pb.dupe(@This(), self, allocator);
    }

    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return pb.json.decode(@This(), input, options, allocator);
    }

    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return pb.json.encode(self, options, allocator);
    }

    // This method is used by std.json
    // internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return pb.json.parse(@This(), allocator, source, options);
    }

    // This method is used by std.json
    // internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return pb.json.stringify(@This(), self, jws);
    }
};
